# Production configuration
# These values will be overridden by environment variables

server:
  port: 8080

spring:
  datasource:
    url: postgresql://postgres:gYoFrbTUICKeWmNKbesQYRIawcDCxYae@postgres.railway.internal:5432/railway
    username: postgres
    password: gYoFrbTUICKeWmNKbesQYRIawcDCxYae
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      # NEVER use 'create' or 'update' in production
      # Use 'validate' once your schema is stable
      ddl-auto: update
    show-sql: false        # disable SQL logging in production
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: 90043579b183876caa0bcfbae97e7a995257a0df1020c06931b7fc130f8c4ccf
  access-token-expiration: 900000
  refresh-token-expiration: 604800000

springdoc:
  swagger-ui:
    enabled: false         # disable Swagger in production
  api-docs:
    enabled: false